### ISSUE TITLE
🐛 BUG: JSX style comment in Markdown

### ISSUE THREAD

**Issue by JulianCataldo** [withastro/prettier-plugin-astro#201] opened 2022-05-25 17:29 UTC
### Describe the Bug

Prettier is transforming
`{/*` into `{/\*`
Also, JSX comments aren't taken into account by the AST / Syntax highlighter, still in Markdown.
They just behave as plain text (but that's another issue)

**Comment by Princesseuh** [comment] 2022-06-24 01:56
Closing as a duplicate of https://github.com/withastro/prettier-plugin-astro/issues/61

**Closed by Princesseuh** 2022-06-24 01:56 UTC
