### ISSUE TITLE
🐛 BUG: Some astro files indented with 4 spaces instead of 2 which is the prettier config setting

### ISSUE THREAD

**Issue by gkatsanos** [withastro/prettier-plugin-astro#351] opened 2023-06-15 16:21 UTC
### Describe the Bug

Some astro files indented with 4 spaces instead of 2 which is the prettier config setting

### Steps to Reproduce

prettierrc:
```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": false,
  "plugins": ["prettier-plugin-astro", "prettier-plugin-tailwindcss"],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```

For some reason the following file is formatted with 4 tabs by the VSCode Astro extension:

```
---
interface Props {
    name: string
    imageUrl: string
    testimonialContent: string
    company: string
}

const { name, imageUrl, testimonialContent, company } = Astro.props
---

<div
    class="carousel-item max-w-[490] md-down:max-w-[240px] bg-white shadow-wlw/200 rounded p-6"
>
    <div class="card">
        <h3
            class="testimonials-item text-2xl font-lato font-bold text-16 leading-150 text-navy-100 mb-3"
        >
            {testimonialContent}
        </h3>
        <div class="profile-info flex items-center gap-3">
            <img
                src={imageUrl}
                alt="Image profile"
                width={56}
                height={56}
                class="flex-none rounded-full"
            />

            <div class="info-content">
                <strong>{name}</strong>
                <p>{company}</p>
            </div>
        </div>
    </div>
</div>;

<style>
    .carousel-item {
        flex: 0 0 100%;
    }

    .testimonials-item {
        width: 100%;
        height: auto;
    }
</style>
```

but when I run the prettier command using the cli, the proper formatting is applied. :

```
./node_modules/p
rettier/bin-prettier.js ./src/components/ --write --plugin=prettier-plugin-astro
```

I don't understand what takes precedence, I don't know how to see which formatter is applied.

**Comment by jiv-e** [comment] 2023-06-26 21:49
I have the same problem.

**Comment by jiv-e** [comment] 2023-06-26 22:08
I found out that the problem is the official VS Code plugin: https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode

If you disable the extension and configure prettier-plugin-astro separately as instructed, it works correctly.

**Comment by jiv-e** [comment] 2023-06-26 22:30
As a workaround you can use the default Prettier config by setting this in your VS Code settings.json:
```
"[astro]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

Where "esbenp.prettier-vscode" Is the default formatter.
`"editor.defaultFormatter": "esbenp.prettier-vscode",`

If you use another default formatter, you should probably use that.

Be sure to configure the prettier-plugin-astro as instructed when not using the VS Code Astro extension. See: https://github.com/withastro/prettier-plugin-astro

**Comment by gkatsanos** [comment] 2023-06-28 04:55
> Be sure to configure the prettier-plugin-astro as instructed when not using the VS Code Astro extension. See: https://github.com/withastro/prettier-plugin-astro

Thank you for the replies and the bug report! Would it be too much to ask to have a plug and play plugin without extra configuration? It shouldn't be that hard :)

**Comment by Princesseuh** [comment] 2023-07-03 09:51
Closing this issue in favor of the language-tools one, since the issue is ultimately there.

> Would it be too much to ask to have a plug and play plugin without extra configuration? It shouldn't be that hard :)

The Prettier plugin itself is plug and play with no extra configuration. The Prettier VS Code extension require additional configuration for any custom languages, that's just how it works - it's outside our reach.

Same thing for the "Recommended configuration" at the top of the README, as indicated it's only necessary because Prettier's plugin auto discovery does not work on pnpm and some other package manager / setup, but it's ultimately optional.

**Closed by Princesseuh** 2023-07-03 09:51 UTC

**Comment by gkatsanos** [comment] 2023-07-04 07:56
I was not condescending at all, not sure how this tone passed in my message. But I don't fully understand the answer. I didn't have to configure Prettier so far for any other framework.. 
I feel there's a differentiation / conflict between Prettier/Eslint PRettier + the Astro extension, right?
If this is something that is already picked-up on and recognized as an issue, all good!

**Comment by Princesseuh** [comment] 2023-07-04 08:41
You might've only used frameworks that Prettier support natively, such as JSX ones or Vue. Svelte for instance require the same configuration we have to work in the Prettier VS Code extension / when using pnpm

> I feel there's a differentiation / conflict between Prettier/Eslint PRettier + the Astro extension, right?

Yes, there's currently an issue where the Astro VS Code extension mistakenly uses VS Code's formatting settings for certain files instead of following the Prettier config

**Comment by gkatsanos** [comment] 2023-07-04 08:48
yep, I use JSX / Vue on most of my projects. Thanks, that clarifies things!
