### ISSUE TITLE
🐛 BUG: inserts space between pre and code, breaks file

### ISSUE THREAD

**Issue by hyperknot** [withastro/prettier-plugin-astro#419] opened 2024-06-13 00:02 UTC
### Describe the Bug

It inserts a newline / space between pre and code tags when inside an if-block.

### Steps to Reproduce

This is still formatted correctly:

```
<>
  <pre
    id="style-url-pre"><code id="style-url-code">https://tiles.openfreemap.org/styles/liberty</code></pre>
</>
```

But if I put it inside an if-block, it breaks the DOM:

```
{
  showStyleURL && (
    <>
      <pre id="style-url-pre">
        <code id="style-url-code">https://tiles.openfreemap.org/styles/liberty</code>
      </pre>
    </>
  )
}
```

**Comment by Princesseuh** [comment] 2024-06-13 07:09
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/308

**Closed by Princesseuh** 2024-06-13 07:09 UTC

**Comment by hyperknot** [comment] 2024-06-13 11:28
And with both of my issues closed, could you help me how can I possibly have this code working?

```
{
  showStyleURL && (
    <pre id="style-url-pre"><code id="style-url-code">https://tiles.openfreemap.org/styles/liberty</code></pre>
  )
}

<script is:inline src="https://unpkg.com/maplibre-gl/dist/maplibre-gl.js"></script>
```
