### ISSUE TITLE
🐛 BUG: <style> is moved inside <body> where applicable

### ISSUE THREAD

**Issue by paulrudy** [withastro/prettier-plugin-astro#260] opened 2022-08-16 02:20 UTC
### Describe the Bug

Apologies if this is not a bug, but:

In components/layouts with <body>...</body>, component/layout styles written outside the main html are moved by the plugin to inside the <body>...</body> structure.

example

### Steps to Reproduce

I expect the following code to remain as is:
```html
<body>
<div>
bla bla bla
</div>
</body>

<style>
div {
  border: 1px solid red;
  }
</style>
```
but instead, the prettier plugin changes it to:

```html
<body>
  <div>bla bla bla</div>
  <style>
    div {
      border: 1px solid red;
    }
  </style>
</body>
```

**Comment by Princesseuh** [comment] 2022-08-16 02:43
Hello, thank you for creating this issue! This is a known bug in our compiler at the moment https://github.com/withastro/compiler/issues/318

Hoping to get that fixed soon 😅 I'll close this issue just so we don't get duplicated issues, but thank you again for creating it!

**Comment by jasikpark** [comment] 2022-08-16 12:06
Is there an issue tracking this for the prettier plugin, or do you consider the compiler issue to count as tracking this?

**Comment by jasikpark** [comment] 2022-08-16 12:32
🤷 ok

I'd argue it's both a "prettier formats incorrectly" issue and then there's an implementation detail of that issue being tracked in the compiler repo as the root cause, so it's two issues since it's two projects that have the bug

since otherwise there's no issue in this repo to close when the bug is fixed by updating the compiler dep

thanks for explaining 🙏

**Comment by Princesseuh** [comment] 2022-08-16 12:36
> 🤷 ok
> 
> I'd argue it's both a "prettier formats incorrectly" issue and then there's an implementation detail of that issue being tracked in the compiler repo as the root cause, so it's two issues since it's two projects that have the bug
> 
> since otherwise there's no issue in this repo to close when the bug is fixed by updating the compiler dep
> 
> thanks for explaining 🙏

That's fair, you've changed my mind!

**Comment by jasikpark** [comment] 2022-09-29 20:33
https://github.com/withastro/prettier-plugin-astro/issues/286 for another repro

**Comment by jasikpark** [comment] 2022-09-29 20:33
https://github.com/withastro/compiler/issues/531 for the relevant compiler issue

**Comment by Princesseuh** [comment] 2022-09-29 20:35
> [withastro/compiler#531](https://github.com/withastro/compiler/issues/531) for the relevant compiler issue

For that one, the relevant compiler issue is this one https://github.com/withastro/compiler/issues/318

**Comment by jasikpark** [comment] 2022-09-29 20:38
ack

**Closed** 2022-10-17 13:02 UTC
Labels: bug, upstream

**Comment by paulrudy** [comment] 2022-10-18 23:01
With the v0.6.0 update, <style>...</style> isn't moved inside <body> 🎉

but unfortunately, in a layout with the following structure:

```html
<html>
  <head>

  </head>
  <body>

  </body>
</html>

<style>
  
</style>
```

<style></style> is being moved inside <html> now:

```html
<html>
  <head>

  </head>
  <body>

  </body>

  <style>
  
  </style>
</html>
```

**Comment by paulrudy** [comment] 2023-01-24 18:55
I'm afraid that at least for me, this bug is back. Specifically [this version](https://github.com/withastro/prettier-plugin-astro/issues/260#issuecomment-1283106997) of the bug, where style blocks are moved inside the closing `</html>` tag.

I'm on astro 2.0.0-beta.2, prettier-plugin-astro 0.7.2

**Comment by Princesseuh** [comment] 2023-01-24 19:33
> I'm afraid that at least for me, this bug is back. Specifically [this version](https://github.com/withastro/prettier-plugin-astro/issues/260#issuecomment-1283106997) of the bug, where style blocks are moved inside the closing `</html>` tag.
> 
> I'm on astro 2.0.0-beta.2, prettier-plugin-astro 0.7.2

Yep, tracked here https://github.com/withastro/prettier-plugin-astro/issues/316

Sorry for the inconvenience, we're currently in the midst of releasing Astro 2.0, so this could take some time to fix, but it's planned!

**Comment by paulrudy** [comment] 2023-01-24 21:35
Oops, should have checked current issues. Thanks!
