### ISSUE TITLE
🐛 BUG: ViewTransitions component breaks `head` tag on format

### ISSUE THREAD

**Issue by benediktms** [withastro/prettier-plugin-astro#409] opened 2024-02-25 18:51 UTC
### Describe the Bug

When adding the `<ViewTransitions/>` component to the head tag in a layout, formatting the file will break the the head and script tags **if it is the last node in the head tag**.

Before format:

```astro
<html lang="en">
  <head>
    // ...
    <ViewTransitions/>
  </head>

  <script is:inline>
    //...
  </script>

  //...
</html>
```

after format:
```astro
<html lang="en">
  <head>
    // ...
    <ViewTransitions/>
    <script is:inline>
      //...
    </script></head
>

  //...
</html>
```

moving the `ViewTransition` component further up (anywhere but last) the head tag make the formatter behave correctly.

```astro
<html lang="en">
  <head>
    // ...
    <ViewTransitions/>
    <title>foo</title>
  </head>

  <script is:inline>
    //...
  </script>

  //...
</html>
```

### Steps to Reproduce

1. `npm init astro` using any template
3. create a layout
4. add a head tag to the layout
5. add a `ViewTransisions` component as the last element in the head tag
6. format the file using prettier
7. see the formatter break the head and script tag

**Comment by Princesseuh** [comment] 2024-02-25 19:42
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/316

**Closed by Princesseuh** 2024-02-25 19:42 UTC
