### ISSUE TITLE
🐛 BUG: Added unnecessary end tag in expression

### ISSUE THREAD

**Issue by kagankan** [withastro/prettier-plugin-astro#277] opened 2022-09-10 08:48 UTC
## Failure Pattern

Probably, the conditions are:

- inside expression
- 2 or more attributes
- `>` is in next line

### Input

```astro
<div>
  {
    (
      <div id="id" class="class"
      >text
      </div>
    )
  }
</div>
```

### Output

```astro
<div>
  {
    (
      <div id="id" class="class"></div>
        text
      </div>
    )
  }
</div>
```

added unnecessary `</div>` .

## Success Patterns

the line ends with `>`

<details>
  <summary>Input</summary>

```astro
<div>
  {
    (
      <div id="id" class="class">
      text</div>
    )
  }
</div>
```
</details>

<details>
  <summary>Output</summary>

```astro
<div>
  {
    (
      <div id="id" class="class">
        text
      </div>
    )
  }
</div>
```
</details>

outside expression

<details>
  <summary>Input</summary>

```astro
<div>
  <div id="id" class="class"
  >text
  </div>
</div>
```
</details>

<details>
  <summary>Output</summary>

```astro
<div>
  <div id="id" class="class">text</div>
</div>
```
</details>

with single attribute

<details>
  <summary>Input</summary>

```astro
<div>
  {
    (
      <div class="class"
      >text
      </div>
    )
  }
</div>
```
</details>

<details>
  <summary>Output</summary>

```astro
<div>
  {(<div class="class">text</div>)}
</div>
```
</details>

## Notes

- I'm using prettier-plugin-astro via astro-vscode v0.24.4.
- my `printWidth` setting is `120`.

### Steps to Reproduce

See `Describe the Bug`

**Comment by Princesseuh** [comment] 2022-09-26 21:09
Hello, it seems like this is not a bug in the Prettier plugin, but in VS Code's auto closing. Setting `html.autoClosingTags` to `false` fixes the issue (but, of course disable tags auto closing). 

Not sure if there's way on our end to fix it, I'll investigate

**Comment by Princesseuh** [comment] 2023-08-11 20:26
The auto closing logic in the extension has been upgraded and it seems like this is not an issue anymore, as such I'll close this issue

**Closed by Princesseuh** 2023-08-11 20:27 UTC
Labels: bug, upstream
