### ISSUE TITLE
🐛 BUG: `Error: unhandled node type: 'expression'`

### ISSUE THREAD

**Issue by jasikpark** [withastro/prettier-plugin-astro#193] opened 2022-05-09 21:47 UTC
### Describe the Bug

A reduced example of code that triggers the bug is:

```astro
{true && <div {...{ style: 'color:red;'}}>hello</div>}
```

which result in this error message:

```
["ERROR" - 4:44:37 PM] Unhandled node type "expression"!
Error: Unhandled node type "expression"!
```

### Steps to Reproduce

Format the above code snippet w/ prettier plugin version `0.1.0-next.4`

**Comment by mvolfik** [comment] 2022-05-10 08:40
Another case of this (not entirely sure if it's the exact same bug though):

```jsx
{["/", "/a"].map((href) => <a {href}>hi</a>)}
```

This is valid Astro, but doesn't format. Replacing `{href}` with `href={href}` works

**Comment by mvolfik** [comment] 2022-05-10 11:03
This doesn't seem too similar to the other cases, so reporting it as well:
```jsx
{a.split("\n").map(x => <p>{x}</p>)}
```
Works when you remove the `\n` from the split pattern

**Comment by ota-meshi** [comment] 2022-05-15 09:22
Hi @mvolfik.
I think the escape issue will probably be resolved in the next pull request.
https://github.com/withastro/compiler/pull/393

**Comment by ota-meshi** [comment] 2022-05-28 09:53
@natemoo-re I have debugged this. There seems to be a problem with the `serialize` method of `@astrojs/compiler/utils`. Serializing the spread attribute returns an unfinished script `"{...}"`.

https://github.com/withastro/compiler/blob/d5dd438d3f0aa5f005e9b4d7127230711ab126a1/packages/compiler/node/utils.ts#L96
I think we probably need to use `attr.name` instead of `attr.value`.

**Comment by jasikpark** [comment] 2022-06-02 17:37
Another case where I get this error is 

```astro
---
---

<p>below is a js-style comment</p>
{/** this is a comment that throws the "unhandled node type: 'expression'" error */}
```

maybe there's a new version I should try?

**Comment by ota-meshi** [comment] 2022-06-03 04:07
It is not fixed in PR. The cause seems to be different. I think we need to open a new issue.

**Comment by simonwiles** [comment] 2022-06-24 22:21
Original issue appears to remain.  I can trigger it with something as simple as:
```astro
{(records.length) ? <Record {record} /> : null}
```
or
```astro
{(records.length) && <Record {record} /> }
```
(using `0.1.1` which includes #223).

**Comment by ota-meshi** [comment] 2022-06-24 22:30
The cause is a shorthand attribute. I have already reported it. #224

**Comment by simonwiles** [comment] 2022-06-24 22:36
Thanks -- apologies for the noise.

**Comment by Princesseuh** [comment] 2022-07-21 17:53
Closing in favor of issues about the specific problem causing this error. This error happens whenever the babel parser is not able to parse an expression, as such it'll happens for multiple reasons that requires different fixes in most cases

**Closed by Princesseuh** 2022-07-21 17:53 UTC
Labels: bug
