### ISSUE TITLE
🐛 BUG: prettier-ignore breaks file

### ISSUE THREAD

**Issue by hyperknot** [withastro/prettier-plugin-astro#420] opened 2024-06-13 00:24 UTC
### Describe the Bug

```
<!-- prettier-ignore -->
{
  showStyleURL && (
    <pre id="style-url-pre">
      <code id="style-url-code">https://tiles.openfreemap.org/styles/liberty</code>
    </pre>
  )
}

<script is:inline src="https://unpkg.com/maplibre-gl/dist/maplibre-gl.js"></script>
```

gets reformatted into:

```
<!-- prettier-ignore -->
{
  showStyleURL && (
    <pre id="style-url-pre">
      <code id="style-url-code">https://tiles.openfreemap.org/styles/liberty</code>
    </pre>
  )
}

script is:inline src="https://unpkg.com/maplibre-gl/dist/maplibre-gl.js"></script>
```

(emphasis is on last lines missing < tag)

### Steps to Reproduce

check snippet

**Comment by Princesseuh** [comment] 2024-06-13 07:10
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/338

(The root cause is the same, even if that issue showcase a different situation)

**Closed by Princesseuh** 2024-06-13 07:10 UTC
