### ISSUE TITLE
🐛 BUG: Adding components into head tag breaks the astro file layout (view transitions)

### ISSUE THREAD

**Issue by IcyFoxe** [withastro/prettier-plugin-astro#406] opened 2024-02-19 14:21 UTC
### Describe the Bug

When you put the `<ViewTransitions />` component to the `<head>` tag, it will break the layout of your .astro component, and put the `<style>` tag inside of your `<html>` tag.

This doesn't happen if you put `<ViewTransitions />` component to your `<body>` element, and while view transitions will still work, its not following the documentation.

### Steps to Reproduce

1. Add View Transition to your Layout.astro component, or any other component that contains `head`, `body` and `style` tags.
```html
---
import { ViewTransitions } from "astro:transitions";
---
<!doctype html>
<html lang="en">
  <head>
    <ViewTransitions />
  </head>
  <body>
  </body>
</html>

<style is:global>
</style>
```
2. Format the document using prettier astro plugin
3. `style` tag will be moved to the `html` tag.

**Comment by Princesseuh** [comment] 2024-02-19 17:04
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/316

**Closed by Princesseuh** 2024-02-19 17:04 UTC
