### ISSUE TITLE
🐛 BUG: incorrect formatting for conditionally nested script tag

### ISSUE THREAD

**Issue by EduardDopler** [withastro/prettier-plugin-astro#361] opened 2023-07-18 10:08 UTC
### Describe the Bug

When combining a logical expression with a script tag, after running prettier the formatting becomes unreadable.

Expected formatting:
```astro
---
const correctedSlug = "demo";
---
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <title>Demo</title>
</head>
<body>
  <main>
    <header>Hello</header>

    {
      correctedSlug && (
        <script
          id="corrected-slug"
          data-corrected-slug={correctedSlug}
          data-product-id={123}
        >
          const script = document.getElementById("corrected-slug");
          const correctedSlug = script.dataset.correctedSlug;
          const productId = script.dataset.productId;
          const correctedPath = correctedSlug + "-" + productId;
          const correctSlugUrl = new URL(correctedPath, window.location.href);
          correctSlugUrl.search = window.location.search;
          correctSlugUrl.hash = window.location.hash;
          console.log(correctSlugUrl);
        </script>
      )
    }
  </main>
</body>
</html>
```

Actual formatting:
```astro
---
const correctedSlug = "demo";
---
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width">
  <title>Demo</title>
</head>
<body>
  <main>
    <header>Hello</header>

    {
      correctedSlug && (
        <script
          id="corrected-slug"
          data-corrected-slug={correctedSlug}
          data-product-id={123}
        >
          const script = document.getElementById("corrected-slug"); const
          correctedSlug = script.dataset.correctedSlug; const productId =
          script.dataset.productId; const correctedPath = correctedSlug + "-" +
          productId; const correctSlugUrl = new URL(correctedPath,
          window.location.href); correctSlugUrl.search = window.location.search;
          correctSlugUrl.hash = window.location.hash;
          window.history.replaceState(null, "", correctSlugUrl);
        </script>
      )
    }
  </main>
</body>
</html>
```

VS Code 1.80.1 on macOS 13.4.1
Node 18.16.1, npm 9.8.0
Astro 2.8.3, prettier-plugin-astro 0.11.0, prettier 3.0

Reproducible also on older Astro, plugin and prettier versions (e.g. Astro 2.2, prettier-plugin-astro 0.8.0 and prettier 2.8.7).

### Steps to Reproduce

see above

**Comment by Princesseuh** [comment] 2023-07-18 10:13
Duplicate of https://github.com/withastro/prettier-plugin-astro/issues/337

**Closed by Princesseuh** 2023-07-18 10:13 UTC
