### ISSUE TITLE
Style and scripts moved into body tag in certain cases 

### ISSUE THREAD

**Issue by ChrisSki** [withastro/prettier-plugin-astro#316] opened 2023-01-20 16:45 UTC
### What version of `astro` are you using?

1.9.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Per the [docs](https://docs.astro.build/en/guides/styling/#import-order) for importing CSS:

>**Tip:** A common pattern in Astro is to import global CSS inside a [Layout component](https://docs.astro.build/en/core-concepts/layouts/). Be sure to import the Layout component before other imports so that it has the lowest precedence.

I tried using a `<style lang="scss">` outside of `<html>` like so:

**src/layouts/BlogPostLayout.astro**

![Screenshot 2023-01-20 at 11 41 33 AM](https://user-images.githubusercontent.com/643408/213754412-b9e4b404-97cc-40a3-90c4-0afbe9a650f2.png)

But was left with this:

![Screenshot 2023-01-20 at 11 41 51 AM](https://user-images.githubusercontent.com/643408/213754475-910f4c36-43e1-474c-9ae4-cf9af543246c.png)

@aFuzzyBear suggested I log this in hope that the Astro Prettier plugin could allow for this and not confuse anyone else 🙂

### Link to Minimal Reproducible Example

na

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by Princesseuh** [comment] 2023-01-20 23:09
Hello, thank you for reporting this issue! I'm pretty sure we had this fixed already in the past, I'll do a proper investigation on Monday, but it is possible that you're using an outdated version of the plugin?

**Comment by ChrisSki** [comment] 2023-01-21 01:09
I'm on 0.7.2 which I think is the latest?

**Comment by Princesseuh** [comment] 2023-01-23 18:41
Hello! After further investigation, this is caused by an issue in the compiler. The previous fix fixed this in most situations, but it seems like there's still an issue when the content of `head` is a component. I'm sorry for the inconvenience!

**Comment by ChrisSki** [comment] 2023-01-23 18:49
All good! I just wanted to bring it up since the Astro docs suggest importing global css into a layout, and done like this it's just a formatting issue. The workaround was simply to build a GlobalStyles component and import that into the Head in my layout, which the docs also suggest. So nothing really wrong here :)

**Comment by HiDeoo** [comment] 2023-03-31 04:41
> there's still an issue when the content of `head` is a component

Another workaround is using this syntax:

```astro
<head>
  {/* https://github.com/withastro/prettier-plugin-astro/issues/316#issuecomment-1400808708 */}
  {() => <Head />}
</head>
```

**Comment by mks-h** [comment] 2023-06-29 12:54
Formatting the file twice puts styles inside the `body` element. Trying to `prettier-ignore` the styles triggers #338, which eats the styles (except for the `lang=scss` attribute, weirdly enough).

**Comment by Princesseuh** [comment] 2023-06-29 13:27
Both issues are unfortunately still blocked upstream. You can keep an eye out on this issue for the style tag moving: https://github.com/withastro/compiler/issues/712

**Comment by shardbearer-shri** [comment] 2023-07-02 05:59
Still facing this issue and i was wondering why my styles intellisense was not working

**Comment by jmegs** [comment] 2024-01-19 20:28
just ran across this same issue in `2.6.2` of the extension, just to provide more evidence it's still happening

**Comment by firxworx** [comment] 2024-01-24 19:53
I'm running latest everything and can confirm this issue remains: astro-prettier-plugin v5.1.3 + astro 4.2.4.

I note the comment above that things are currently blocked upstream per https://github.com/withastro/compiler/issues/712.

@jmegs note that this happens with any component in the head not just `<ViewTransition>` (in case that helps you).

I can also confirm that this plugin appears to _ignore_ `prettier-ignore` directives as documented in https://prettier.io/docs/en/ignore.html.

No combinations of `<!-- prettier-ignore -->` or `<!-- prettier-ignore-start -->` + `<!-- prettier-ignore-end -->` that I tried could get prettier to leave this alone.

I also tried moving my `<style>...</style>` to its own Astro component and the issue still appears, so whatever underlying pattern/regex is not specifically limited to `<style>` and <script>` tags.

I'm surprised this isn't tripping people up all over the place!!

**Comment by raae** [comment] 2024-03-04 21:11
I also see this when adding <ViewTransitions /> to the head.

Astro extension v2.7.5

**Comment by cprcrack** [comment] 2024-03-07 19:20
Can I suggest this bug to be considered as higher priority? P3 / minor bug / edge case doesn't seem to make it justice.

**Comment by Princesseuh** [comment] 2024-03-07 19:24
There's already a PR in flight to fix this issue, bumping the priority at this point wouldn't change anything.

**Comment by MiguelJAS** [comment] 2024-04-18 20:36
Can we bump the priority for this? Thanks!

**Comment by Princesseuh** [comment] 2024-04-19 04:14
> Can we bump the priority for this? Thanks!

Please read the comment right above yours.

**Comment by MoltenCoffee** [comment] 2024-06-02 19:45
The workaround by @rbsummers seems to work for me as well!

**Comment by thedanbaird** [comment] 2024-07-12 02:56
The workaround from @rbsummers works for me too - would be great to bump the priority of this up though.

**Comment by Princesseuh** [comment] 2024-07-18 21:11
This was fixed in the last version!

**Closed by Princesseuh** 2024-07-18 21:11 UTC
Labels: ecosystem: compiler, - P3: minor bug
