### ISSUE TITLE
🐛 BUG: the plugin throws `(0 , import__2.default) is not a function` when using JavaScript `map`, forEach`, etc...

### ISSUE THREAD

**Issue by JustinyAhin** [withastro/prettier-plugin-astro#184] opened 2022-04-28 08:10 UTC
### Describe the Bug

When you add any JavaScript expression like `map`, `forEach` in an `.astro` file, the formatter plugin throws an error `ParseError: (0 , import__2.default) is not a function`.

For example, when you add 
```
const items = ["Dog", "Cat", "Platipus"];

<ul>
  {items.map((item) => (
    <li>{item}</li>
  ))}
</ul>
```
you get this error.

The above example come https://docs.astro.build/en/core-concepts/astro-components/#dynamic-jsx-expressions.

### Steps to Reproduce

1. Go to https://stackblitz.com/edit/github-wanuv4-s6gjnn?file=src%2Fpages%2Findex.astro
2. Run `npm run format` and check the console output

**Comment by heinthanth** [comment] 2022-05-07 13:49
Yes ... the same thing happened to me!

**Comment by leader22** [comment] 2022-05-10 05:21
```astro
---
const items = ["Dog", "Cat", "Platipus"];
---

<!-- OK -->
{items.length === 0 ? "Empty!" : `{items.length} items!`}
<!-- NG -->
{items.length === 0 ? (<p>Empty!</p>) : (<p>{items.length} items!</p>)}
```

Conditional rendering also throws the same error w/ JSX.

**Comment by SteveALee** [comment] 2022-05-14 16:32
Yup, pretty much first bit of real code I tried

To get reporducable I tried an example in the docs

```JSX
--
const items = ["Dog", "Cat", "Platipus"];
---
<ul>
  {items.map((item) => (
    <li>{item}</li>
  ))}
</ul>
```

Here's the full output for me (including prettier confg)

```bash
["INFO" - 5:11:43 PM] Formatting file:///home/wsl/astro-chords/src/components/SiteNavigation.astro
["INFO" - 5:11:43 PM] Using config file at '/home/wsl/astro-chords/.prettierrc'
["INFO" - 5:11:43 PM] Using ignore file (if present) at /home/wsl/astro-chords/.prettierignore
["INFO" - 5:11:43 PM] File Info:
{
  "ignored": false,
  "inferredParser": "astro"
}
["INFO" - 5:11:43 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:11:43 PM] Prettier Options:
{
  "filepath": "/home/wsl/astro-chords/src/components/SiteNavigation.astro",
  "parser": "astro",
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true,
  "singleAttributePerLine": true,
  "astroAllowShorthand": false
}
["ERROR" - 5:11:43 PM] Error formatting document.
ParseError: (0 , import__2.default) is not a function
	at error (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/utils/error.js:51:15)
	at Parser.error (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/index.js:102:30)
	at Parser.acorn_error (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/index.js:96:10)
	at read_expression (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/read/expression.js:230:12)
	at mustache (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/state/mustache.js:321:54)
	at new Parser (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/index.js:62:15)
	at Object.parse (/home/wsl/astro-chords/node_modules/@astrojs/parser/dist/parse/index.js:192:18)
	at Object.parse (/home/wsl/astro-chords/node_modules/prettier-plugin-astro/dist/index.js:14:32)
	at Object.parse (/home/wsl/astro-chords/node_modules/prettier/index.js:7361:23)
	at coreFormat (/home/wsl/astro-chords/node_modules/prettier/index.js:8672:18)
	at formatWithCursor2 (/home/wsl/astro-chords/node_modules/prettier/index.js:8864:18)
	at /home/wsl/astro-chords/node_modules/prettier/index.js:39174:12
	at Object.format (/home/wsl/astro-chords/node_modules/prettier/index.js:39188:12)
	at t.default.format (/home/wsl/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13427)
	at async t.PrettierEditProvider.provideEdits (/home/wsl/.vscode-server/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10134)
	at async x.provideDocumentFormattingEdits (/home/wsl/.vscode-server/bin/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/out/vs/workbench/api/node/extensionHostProcess.js:83:105121)
["INFO" - 5:11:43 PM] Formatting completed in 0.012ms.
```

**Comment by SlicedSilver** [comment] 2022-05-16 19:23
The current release of this plugin seems to be using the old Astro parser. You could try switching to the beta version of this plugin by running `npm i -D prettier-plugin-astro@next` which uses the new Astro compiler. In my experience this fixes the issue mentioned here.

However, if you are unable to use the beta version (due to different issues) then you could try this hacky workaround below.

The issue is that any piece of nested Astro markup can't be parsed because the parser import (`import__2.default`) is resolving to an empty object. The code is within the `@astrojs/parser` package which has now been deprecated, and I'm not entirely sure why it's not importing correctly.

 I'm switching to the beta version, and the following workaround was discovered while trying to find the bug (and before I knew there was a beta version available).

### Hacky Temp Fix (use at your own risk)
in `node_modules/@astrojs/parser/dist/index.js`, 
after this line: 
  `var import_parse = __toESM(require("./parse/index.js"));` 
add the following line:
  `global.astro_parser_import = import_parse;`

and in `node_modules/@astrojs/parser/dist/parse/read/expression.js`, 
replace this line: 
`const ast = (0, import__2.default)(source);`
with this:
`const ast = (0, global.astro_parser_import.default)(source);`

**Closed** 2022-06-24 15:33 UTC
